kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-hpa
  namespace: nginx-hpa
  labels:
    app: nginx-hpa
    app.kubernetes.io/component: nginx-hpa
    app.kubernetes.io/instance: nginx-hpa
    app.kubernetes.io/part-of: nginx-hpa-app
    app.openshift.io/runtime: nginx
    app.openshift.io/runtime-namespace: nginx-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hpa
  template:
    metadata:
      labels:
        app: nginx-hpa
        deploymentconfig: nginx-hpa
    spec:
      serviceAccountName: custom-metrics-apiserver
      containers:
        - name: nginx-exporter
          image: 'nginx/nginx-prometheus-exporter:0.9.0'
          ports:
            - containerPort: 9113
              protocol: TCP
          imagePullPolicy: IfNotPresent
        - name: nginx-hpa
          image: quay.io/casimon/nginx-hpa
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 150Mi
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
