apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: nginx-hpa
  name: nginx-hpa
  labels:
    app: nginx-hpa
    app.kubernetes.io/component: nginx-hpa
    app.kubernetes.io/instance: nginx-hpa
    app.kubernetes.io/part-of: nginx-hpa-app
    app.openshift.io/runtime: nginx
    app.openshift.io/runtime-namespace: nginx-hpa
  annotations:
    metric-config.external.prometheus-query.prometheus/nginx_http_requests_total: max(rate(nginx_http_requests_total{namespace="nginx-hpa"}[1m]))
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-hpa
  metrics:
  - type: External
    external:
      metric:
        name: prometheus-query
        selector:
          matchLabels:
            query-name: nginx_http_requests_total
      target:
        type: Value
        value: "10"