apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: nginx-hpa
  name: nginx-hpa
  namespace: nginx-hpa
spec:
  endpoints:
  - interval: 30s
    port: 9113-tcp
    scheme: http
  selector:
    matchLabels:
      app: nginx-hpa